[project]
name = "anysearch"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "duckduckgo-search>=6.4.1",
    "groq>=0.13.0",
    "langchain-cerebras>=0.3.0",
    "langchain-core>=0.3.24",
    "litserve>=0.2.5",
]
